name: Build Begonia Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v3
        with:
          repository: Nova-Kernels/kernel_xiaomi_mt6785
          ref: begonia-a13

      - name: Setup environment
        run: |
          sudo apt update
          sudo apt install -y git bc build-essential libssl-dev \
            libc6-dev libncurses5-dev libelf-dev ccache \
            python3 clang llvm lld flex bison zip unzip

      - name: Clone Proton Clang
        run: |
          git clone --depth=1 https://github.com/kdrag0n/proton-clang clang

      - name: Build kernel
        run: |
          export PATH=$GITHUB_WORKSPACE/clang/bin:$PATH
          export ARCH=arm64
          export SUBARCH=arm64
          export KBUILD_BUILD_USER=github
          export KBUILD_BUILD_HOST=actions

          make O=out begonia_defconfig
          make -j$(nproc --all) O=out \
            CC=clang \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-gnueabi-

      - name: Pack AnyKernel3
        run: |
          git clone https://github.com/osm0sis/AnyKernel3
          cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
          cd AnyKernel3
          zip -r9 Begonia-Kernel.zip *

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Begonia-Kernel-ZIP
          path: AnyKernel3/Begonia-Kernel.zip
